ALTER TABLE invoice_drafts ADD COLUMN IF NOT EXISTS total_sum NUMERIC(14,2) NOT NULL DEFAULT 0;
ALTER TABLE invoice_drafts ADD COLUMN IF NOT EXISTS header_signature TEXT;
ALTER TABLE invoice_drafts ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE invoice_drafts ALTER COLUMN expires_at SET DEFAULT NOW() + INTERVAL '1 hour';